### ISSUE TITLE
database

### ISSUE THREAD

**Issue by ardelldio** [gedelumbung/HospitalManagement#1]
tidak disertakan database

**Comment by gedelumbung** [comment]
database hilang di laptop lama, mungkin ke depan, repo ini akan saya hapus

**Comment by ardelldio** [comment]
makasih gan

2014-11-17 20:59 GMT+07:00 Gede Lumbung notifications@github.com:

**Comment by bentcaem** [comment]
Om databasenya ga disertakan?

**Comment by gedelumbung** [comment]
gak ada

**Comment by bentcaem** [comment]
kenapa om?kyknya ciamik nih

**Comment by gedelumbung** [comment]
cuma nitip backup aja

**Comment by andridgitalbox** [comment]
ditunggu database dong om :dancers:
